#importing common packages 
import yt 
import numpy as np 
import matplotlib.pyplot as plt

#yt names for stuff
t=('gas','bx_hat')
yt_by_hat=('gas','by_hat')
yt_bz_hat=('gas','bz_hat')
yt_bx_over_rho=('gas','bx_over_rho')
yt_by_over_rho=('gas','by_over_rho')
yt_bz_over_rho=('gas','bz_over_rho')
yt_cell_volume = ('gas','cell_volume')
yt_cell_mass = ('gas','cell_mass')
yt_particle_pos_x = ('all','particle_position_x')
yt_particle_pos_y = ('all','particle_position_y')
yt_particle_pos_z = ('all','particle_position_z')
yt_particle_position = ('all','particle_position')
yt_particle_velocity = ('all','particle_velocity')
yt_velocity_x = ('gas','velocity_x')
yt_velocity_y = ('gas','velocity_y')
yt_velocity_z = ('gas','velocity_z')
yt_radius = ('index','radius')
yt_magnetic_field_x = ('gas','magnetic_field_x')
yt_magnetic_field_y = ('gas','magnetic_field_y')
yt_magnetic_field_z = ('gas','magnetic_field_z')
yt_particle_index = ('all','particle_index')
yt_density = ('gas','density')
yt_gas_pressure = ('gas','gas_pressure')
yt_pressure = ('gas','pressure')
yt_velocity_divergence=('gas','velocity_divergence')
yt_pressure_work = ('gas','pressure_work')
yt_dpdx=('gas','dpdx')
yt_dpdy=('gas','dpdy')
yt_dpdz=('gas','dpdz')
yt_pressure_accel_mag = ('gas','pressure_accel_mag')
yt_grav_x = ('gas','grav_x')
yt_grav_y = ('gas','grav_y')
yt_grav_z = ('gas','grav_z')
yt_gravity_work=('gas','gravity_work')
yt_grav_norm = ('gas','gravity_norm')
yt_grav_energy = ('gas','grav_energy')
yt_abs_grav_energy = ('gas','abs_grav_energy')
yt_therm_energy=('gas','therm_energy')
yt_kinetic_energy=('gas','kinetic_energy')
yt_momentum_flux=('gas','momentum_flux')
yt_velocity_magnitude=('gas','velocity_magnitude')
yt_magnetic_field_strength=('gas','magnetic_field_strength')
yt_x = ('gas','x')
yt_y = ('gas','y')
yt_z = ('gas','z')
yt_gravpotential=('enzo','GravPotential')
yt_grav_potential=('enzo','Grav_Potential')
yt_potential_field = ('enzo','PotentialField')
yt_grav_energy = 'gas', 'grav_energy'
yt_abs_grav_energy = 'gas', 'abs_grav_energy'
yt_therm_energy = 'gas','therm_energy'
